name: chaton
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.2.7
  provider: ^6.1.5
  image_picker: ^1.1.2
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  flutter_chat_ui: ^2.5.2
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
      - images/
    
