// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04y44-9k0bw4V5B2bKT1NBdoNGwnt2Y0',
    appId: '1:488617010504:web:73ba4d43106ee2855a7f7d',
    messagingSenderId: '488617010504',
    projectId: 'quickchat-d9444',
    authDomain: 'quickchat-d9444.firebaseapp.com',
    storageBucket: 'quickchat-d9444.firebasestorage.app',
    measurementId: 'G-SWXSK6QYHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxWUKnVzAidQy0Q1DKveiEKtPlSIW1i9g',
    appId: '1:488617010504:android:d3590beff4cdd8e05a7f7d',
    messagingSenderId: '488617010504',
    projectId: 'quickchat-d9444',
    storageBucket: 'quickchat-d9444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0eAQWsv00cm_HwQJRuSrE1SYoEgttDuM',
    appId: '1:488617010504:ios:172a0c73de9f80565a7f7d',
    messagingSenderId: '488617010504',
    projectId: 'quickchat-d9444',
    storageBucket: 'quickchat-d9444.firebasestorage.app',
    iosBundleId: 'com.example.chaton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0eAQWsv00cm_HwQJRuSrE1SYoEgttDuM',
    appId: '1:488617010504:ios:172a0c73de9f80565a7f7d',
    messagingSenderId: '488617010504',
    projectId: 'quickchat-d9444',
    storageBucket: 'quickchat-d9444.firebasestorage.app',
    iosBundleId: 'com.example.chaton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB04y44-9k0bw4V5B2bKT1NBdoNGwnt2Y0',
    appId: '1:488617010504:web:fe9351f78cfbf32b5a7f7d',
    messagingSenderId: '488617010504',
    projectId: 'quickchat-d9444',
    authDomain: 'quickchat-d9444.firebaseapp.com',
    storageBucket: 'quickchat-d9444.firebasestorage.app',
    measurementId: 'G-2S78RK3YF7',
  );
}
